/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'МClue': typeof import('./components/МClue.vue')['default']
    Clue: typeof import('./components/Clue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VClue: typeof import('./components/VClue.vue')['default']
    VForm: typeof import('./components/VForm.vue')['default']
    VUser: typeof import('./components/VUser.vue')['default']
  }
}
